(function(root,factory){const api=factory(root.AtomPromptRegistry||(typeof require==='function'?require('./field-registry.js'):null));if(typeof module==='object'&&module.exports)module.exports=api;root.AtomPromptRail=api;if(root.document)root.addEventListener('load',()=>api.mount(root.document));})(typeof globalThis==='object'?globalThis:this,function(Registry){
'use strict';
const CANDIDATE='CANDIDATE_DRAFT — NOT ADMITTED';
const ANSWER_STATUSES=['UNANSWERED','PROPOSED','ACCEPTED','REVISED','DEFERRED','REJECTED'];
const PROMPT_STATUSES=['UNCONFIGURED','DRAFT','TESTED','LOCKED'];
const clone=x=>JSON.parse(JSON.stringify(x));
const uuid=()=>{if(globalThis.crypto?.randomUUID)return globalThis.crypto.randomUUID();throw new Error('Secure application UUID generation is unavailable');};
const hash=async text=>{if(globalThis.crypto?.subtle){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');}let h=2166136261;for(const c of text)h=Math.imul(h^c.charCodeAt(0),16777619);return `fnv1a-${(h>>>0).toString(16)}`;};
class AppendOnlyStore{
 constructor(storage,key='atom-prompt-workbench/v1'){this.storage=storage;this.key=key;this.state=this.load();}
 load(){try{return JSON.parse(this.storage?.getItem(this.key))||{events:[],prompts:{},runs:[],discoveries:[],packet:null};}catch{return {events:[],prompts:{},runs:[],discoveries:[],packet:null};}}
 append(type,payload){const event=Object.freeze({event_uuid:uuid(),type,timestamp:new Date().toISOString(),payload:clone(payload)});this.state.events.push(event);this.save();return event;}
 save(){this.storage?.setItem(this.key,JSON.stringify(this.state));}
 history(type,key){return this.state.events.filter(e=>e.type===type&&(!key||e.payload.field_key===key||e.payload.section===key));}
}
function validatePacket(packet,enabledKeys=[]){const errors=[];if(!packet||typeof packet!=='object')errors.push('Response is not an object');if(packet?.candidate_packet_status!==CANDIDATE)errors.push('Candidate authority boundary is missing or invalid');if(!Array.isArray(packet?.field_results))errors.push('field_results must be an array');if(!Array.isArray(packet?.open_discoveries))errors.push('open_discoveries must be an array');for(const result of packet?.field_results||[]){if(!result.field_key)errors.push('A field result has no stable field_key');if(typeof result.confidence!=='number'||result.confidence<0||result.confidence>1)errors.push(`${result.field_key}: confidence must be between 0 and 1`);if(!ANSWER_STATUSES.includes(result.answer_status))errors.push(`${result.field_key}: invalid answer_status`);if(!Array.isArray(result.source_anchors))errors.push(`${result.field_key}: source_anchors must be an array`);}for(const k of enabledKeys)if(!(packet?.field_results||[]).some(x=>x.field_key===k&&x.enabled!==false))errors.push(`${k}: enabled field is missing`);return {valid:errors.length===0,errors};}
async function composePrompt({globalPrompt,builderPrompt,sectionPrompt,fieldPrompt,sourceText,sourceCoordinates,acceptedContext,responseSchema}){return [
`[GLOBAL GOVERNANCE]\n${globalPrompt}`,`[ATOM BUILDER SYSTEM]\n${builderPrompt}`,`[SECTION]\n${sectionPrompt}`,`[FIELD]\n${fieldPrompt}`,`[PRESERVED SOURCE]\n${sourceText}`,`[VERIFIED COORDINATES]\n${sourceCoordinates}`,`[HUMAN-ACCEPTED CONTEXT]\n${JSON.stringify(acceptedContext||{},null,2)}`,`[EXACT RESPONSE SCHEMA]\n${JSON.stringify(responseSchema,null,2)}`].join('\n\n');}
const RESPONSE_SCHEMA={builder_run_uuid:'APPLICATION_GENERATED_UUID',prompt_versions:{global:'version/hash',builder:'version/hash',sections:{},fields:{}},field_results:[{field_key:'stable key',enabled:true,suggested_value:null,allowed_values:[],rationale:'',source_anchors:[],confidence:0,warnings:[],answer_status:'PROPOSED'}],open_discoveries:[{discovery_uuid:'APPLICATION_GENERATED_UUID',question_or_finding:'',reason_no_current_field:'',source_anchors:[],candidate_status:CANDIDATE}],candidate_packet_status:CANDIDATE};
async function createBuilderRequest(config){const runId=uuid(),fields=config.fields.filter(x=>x.enabled!==false);const fieldPrompts={};for(const f of fields)fieldPrompts[f.key]={code:f.code,section:f.section,purpose:f.purpose,question:f.prompt||f.question,expected_type:f.type,allowed_values:f.allowedValues||[]};return {pass:'BUILDER',builder_run_uuid:runId,authority:CANDIDATE,global_prompt:config.globalPrompt,builder_prompt:config.builderPrompt,prompt_versions:config.promptVersions,enabled_sections:Object.keys(config.sections).filter(k=>config.sections[k].enabled!==false),section_prompts:Object.fromEntries(Object.entries(config.sections).map(([key,value])=>[key,value.prompt])),field_prompts:fieldPrompts,preserved_source:{text:config.sourceText,coordinates:config.sourceCoordinates},accepted_context:config.acceptedContext||{},response_schema:RESPONSE_SCHEMA};}
function normalizePacket(raw,runId,promptVersions){if(!raw||typeof raw!=='object')throw new Error('Malformed builder response');const packet=clone(raw);packet.builder_run_uuid=runId;packet.prompt_versions=promptVersions;packet.candidate_packet_status=CANDIDATE;packet.field_results=(packet.field_results||[]).map(x=>({...x,answer_status:'PROPOSED'}));packet.open_discoveries=(packet.open_discoveries||[]).map(x=>({...x,discovery_uuid:uuid(),candidate_status:CANDIDATE}));return packet;}
async function runTwoPass(config,provider,store){const req=await createBuilderRequest(config);let rawBuilder,rawAudit;try{rawBuilder=await provider('builder',req);const proposed=normalizePacket(rawBuilder,req.builder_run_uuid,req.prompt_versions);const validation=validatePacket(proposed,config.fields.filter(f=>f.enabled!==false).map(f=>f.key));if(!validation.valid)throw new Error(`Builder response invalid: ${validation.errors.join('; ')}`);const auditReq={pass:'AUDIT_REPAIR',builder_run_uuid:req.builder_run_uuid,authority:CANDIDATE,current_candidate_packet:proposed,audit_for:['anchors','fragments','duplicates','same_argumentative_job','contradictions','claim_mode','strengthening_or_weakening','evidence_proof_confusion','forced_fields','open_questions'],response_schema:{corrections:[],warnings:[],suggested_rulings:[],repaired_candidate_packet:RESPONSE_SCHEMA}};rawAudit=await provider('audit',auditReq);if(!rawAudit?.repaired_candidate_packet)throw new Error('Audit response did not include repaired_candidate_packet');const repaired=normalizePacket(rawAudit.repaired_candidate_packet,req.builder_run_uuid,req.prompt_versions);const audited=validatePacket(repaired,config.fields.filter(f=>f.enabled!==false).map(f=>f.key));if(!audited.valid)throw new Error(`Audit response invalid: ${audited.errors.join('; ')}`);store?.append('MODEL_RUN',{builder_run_uuid:req.builder_run_uuid,request:req,raw_builder:rawBuilder,parsed_builder:proposed,audit_request:auditReq,raw_audit:rawAudit,repaired_packet:repaired});if(store){store.state.packet=repaired;store.save();}return {request:req,proposal:proposed,audit:rawAudit,packet:repaired};}catch(error){store?.append('MODEL_FAILURE',{builder_run_uuid:req.builder_run_uuid,request:req,raw_builder:rawBuilder,raw_audit:rawAudit,error:String(error)});throw error;}}
async function runException(config,scope,provider,store){if(!scope||!['field','section'].includes(scope.type)||!scope.key)throw new Error('Exception regeneration requires a field or section key');if(!store?.state.packet)throw new Error('Exception regeneration requires the current candidate packet');const request={pass:'EXCEPTION_REGENERATION',builder_run_uuid:store.state.packet.builder_run_uuid,scope,authority:CANDIDATE,current_candidate_packet:clone(store.state.packet),preserved_source:{text:config.sourceText,coordinates:config.sourceCoordinates},accepted_context:config.acceptedContext||{},response_schema:RESPONSE_SCHEMA};let raw;try{raw=await provider('regenerate',request);const packet=normalizePacket(raw?.repaired_candidate_packet||raw,request.builder_run_uuid,store.state.packet.prompt_versions);const validation=validatePacket(packet);if(!validation.valid)throw new Error('Regeneration response invalid: '+validation.errors.join('; '));store.append('MODEL_EXCEPTION_RUN',{scope,request,raw,parsed_packet:packet});store.state.packet=packet;store.save();return packet;}catch(error){store.append('MODEL_FAILURE',{scope,request,raw,error:String(error)});throw error;}}
function addDiscovery(store,item){const discovery={discovery_uuid:uuid(),question_or_finding:item.question_or_finding,reason_no_current_field:item.reason_no_current_field||'NO CURRENT FIELD',source_anchors:item.source_anchors||[],provenance:item.provenance||'HUMAN',run_receipt:item.run_receipt||null,candidate_status:CANDIDATE};store.state.discoveries.push(discovery);store.append('DISCOVERY_CREATED',discovery);return discovery;}
function decideField(store,fieldKey,status,value,meta={}){if(!['ACCEPTED','REVISED','DEFERRED','REJECTED'].includes(status))throw new Error('Invalid human decision');const decision={field_key:fieldKey,status,value,authority:CANDIDATE,...meta};store.append('HUMAN_FIELD_DECISION',decision);return decision;}
function bulkDecide(store,selections,status,confirmed){if(!confirmed||!Array.isArray(selections)||!selections.length)throw new Error('Bulk decisions require explicit selection and confirmation');const snapshot=clone(store.state);try{const batch=uuid();return selections.map(x=>decideField(store,x.field_key,status,x.value,{batch_uuid:batch}));}catch(e){store.state=snapshot;store.save();throw e;}}
function applyAcceptedValue(control,value){if(!control)return;const normalized=typeof value==='string'?value:Array.isArray(value)?value.join(', '):JSON.stringify(value);if('value' in control){control.value=normalized;control.dispatchEvent(new Event('input',{bubbles:true}));control.dispatchEvent(new Event('change',{bubbles:true}));return;}control.dataset.acceptedValue=normalized;const option=[...control.querySelectorAll('[data-v],button')].find(x=>(x.dataset.v||x.textContent||'').trim()===normalized);option?.click();}
async function endpointProvider(endpoint,pass,request){const response=await fetch(`${endpoint.replace(/\/$/,'')}/${pass}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(request)});const raw=await response.text();if(!response.ok)throw new Error(`${pass} failed (${response.status}): ${raw}`);try{return JSON.parse(raw);}catch{throw new Error(`${pass} returned malformed JSON`);}}
function mount(doc){
 const store=new AppendOnlyStore(globalThis.localStorage);const atomContainer=doc.getElementById('ac');if(!atomContainer)return;
 const command=doc.createElement('aside');command.className='prompt-command';command.innerHTML=`<h2>ATOM Builder Prompt Rail · <span class="candidate-boundary">${CANDIDATE}</span></h2><div class="prompt-command-row"><label>API endpoint <input id="prompt-endpoint" type="url" value="/api/atom-builder"></label><button id="run-builder">Run Builder + Audit</button><button id="accept-all-proposals" type="button">Accept All Proposals Into Draft</button><button id="toggle-sections">Section prompts</button><button id="toggle-discovery">Questions Beyond the Schema</button><span id="prompt-run-status"></span></div><div id="section-prompts" class="section-prompts prompt-hidden"></div><div id="discovery-commons" class="discovery-commons prompt-hidden"><h3>Discovery Commons</h3><p>Keep discoveries unclassified when no field honestly fits.</p><textarea id="discovery-text" placeholder="Question, finding, tension, novel relationship, or candidate field"></textarea><input id="discovery-anchor" placeholder="Verified source anchor (optional)"><button id="add-open-discovery">Add as NO CURRENT FIELD</button><div id="discovery-list"></div></div>`;atomContainer.before(command);
 const sectionBox=command.querySelector('#section-prompts');for(const s of Object.values(Registry.SECTION_PROMPTS)){const saved=store.state.prompts[`section:${s.key}`];sectionBox.insertAdjacentHTML('beforeend',`<div class="section-card" data-section="${s.key}"><label><input type="checkbox" checked> Enable ${s.label}</label><textarea>${saved?.prompt||s.prompt}</textarea><button data-save-section>Save new version</button><span>${saved?.version||s.version}</span></div>`);}sectionBox.onclick=e=>{if(!e.target.matches('[data-save-section]'))return;const card=e.target.closest('[data-section]'),key=card.dataset.section,prompt=card.querySelector('textarea').value;const version={version:`${key}-${Date.now()}`,prompt,hash_pending:true};store.state.prompts[`section:${key}`]=version;store.append('SECTION_PROMPT_VERSION',{section:key,...version});card.querySelector('span').textContent=version.version;};
 command.querySelector('#toggle-sections').onclick=()=>sectionBox.classList.toggle('prompt-hidden');command.querySelector('#toggle-discovery').onclick=()=>command.querySelector('#discovery-commons').classList.toggle('prompt-hidden');
 const renderDiscoveries=()=>{command.querySelector('#discovery-list').innerHTML=store.state.discoveries.map(d=>`<div class="discovery-item"><b>${d.candidate_status}</b><br>${escapeHtml(d.question_or_finding)}<br><small>${d.discovery_uuid} · ${escapeHtml(d.reason_no_current_field)}</small></div>`).join('');};renderDiscoveries();command.querySelector('#add-open-discovery').onclick=()=>{const text=command.querySelector('#discovery-text').value.trim();if(!text)return;addDiscovery(store,{question_or_finding:text,source_anchors:[command.querySelector('#discovery-anchor').value].filter(Boolean)});command.querySelector('#discovery-text').value='';renderDiscoveries();};
 const attached=new WeakSet();function attach(){const controls=[...atomContainer.querySelectorAll('[data-f]'),...atomContainer.querySelectorAll('.ax .tg[data-key]:first-of-type')];controls.forEach((control,i)=>{const field=control.closest('.field, .ax');if(!field||attached.has(field))return;attached.add(field);const key=control.dataset.f||control.dataset.key,def=Registry.fieldDefinition(key,i,field.querySelector('label')?.textContent.trim());const saved=store.state.prompts[`field:${key}`];const rail=doc.createElement('details');rail.className='prompt-rail';rail.dataset.fieldKey=key;rail.innerHTML=railMarkup(def,saved);field.prepend(rail);wireRail(rail,control,def,store);});}new MutationObserver(attach).observe(atomContainer,{childList:true,subtree:true});attach();
 command.querySelector('#accept-all-proposals').onclick=()=>{const status=command.querySelector('#prompt-run-status');let accepted=0;for(const rail of doc.querySelectorAll('.prompt-rail')){if(rail.querySelector('.answer-status')?.textContent!=='PROPOSED')continue;const control=rail.parentElement.querySelector('[data-f],[data-key]');if(!control||control.dataset.proposedValue===undefined)continue;const suggestion=rail.querySelector('.controlled-suggestion');const value=suggestion?.value||control.dataset.proposedValue;if(value==='')continue;applyAcceptedValue(control,value);decideField(store,rail.dataset.fieldKey,'ACCEPTED',value,{prompt_version:store.state.prompts[`field:${rail.dataset.fieldKey}`]?.version||'draft',bulk:true});rail.querySelector('.answer-status').textContent='ACCEPTED';accepted++;}status.className='';status.textContent=`${accepted} proposals copied into the draft — still NOT ADMITTED`;};
 command.querySelector('#run-builder').onclick=async()=>{const status=command.querySelector('#prompt-run-status');status.className='';status.textContent='Running builder…';try{const config=collectConfig(doc,store);if(!config.sourceText.trim())throw new Error('Paste the preserved source into Raw Statement before running the API.');const endpoint=command.querySelector('#prompt-endpoint').value;const result=await runTwoPass(config,(pass,req)=>endpointProvider(endpoint,pass,req),store);applyResults(doc,result.packet,store);status.textContent='Audited candidate packet ready — NOT ADMITTED';renderDiscoveries();}catch(e){status.textContent=`Failure: ${e.message}`;status.className='prompt-error';}};
}
function railMarkup(def,saved){const prompt=saved?.prompt||def.question,status=saved?.status||'UNCONFIGURED';return `<summary><span class="prompt-code">${def.code}</span><span class="prompt-badge prompt-status">${status}</span><span class="prompt-badge answer-status">UNANSWERED</span><span class="prompt-spacer"></span><label><input class="rail-enabled" type="checkbox" checked> enabled</label><button class="rail-generate" type="button">Generate</button></summary><div class="prompt-detail"><b>Purpose:</b> ${escapeHtml(def.purpose)}<label>Editable field prompt<textarea class="field-prompt">${escapeHtml(prompt)}</textarea></label><label>Inherited section system prompt<textarea class="inherited" readonly>${escapeHtml(Registry.SECTION_PROMPTS[def.section]?.prompt||'')}</textarea></label><b>Expected:</b> ${def.type}${def.allowedValues.length?` · ${def.allowedValues.join(', ')}`:''}<h4>Effective composed prompt</h4><pre class="prompt-effective">Expand or edit to preview.</pre><h4>Proposed answer</h4>${def.allowedValues.length?`<select class="controlled-suggestion">${def.allowedValues.map(v=>`<option>${v}</option>`).join('')}</select>`:''}<div class="prompt-proposal">No proposal.</div><p class="receipt">No run receipt · no verified anchors.</p><div class="prompt-actions"><button data-action="accept">Accept</button><button data-action="revise">Revise</button><button data-action="reject">Reject</button><button data-action="defer">Defer</button><button data-action="regenerate">Regenerate</button><button data-action="lock">Lock Prompt</button></div><h4>Append-only history</h4><div class="prompt-history">No history.</div></div>`;}
function wireRail(rail,control,def,store){const prompt=rail.querySelector('.field-prompt'),effective=rail.querySelector('.prompt-effective');const preview=()=>{effective.textContent=`GLOBAL → BUILDER → ${Registry.SECTION_PROMPTS[def.section]?.version||def.section} → ${def.code}\n\n${prompt.value}\n\nPreserved source + verified coordinates + accepted context + exact JSON schema are appended at run time.`;};rail.addEventListener('toggle',preview);prompt.oninput=()=>{rail.querySelector('.prompt-status').textContent='DRAFT';preview();};rail.querySelector('.rail-generate').onclick=e=>{e.preventDefault();rail.open=true;document.querySelector('#run-builder')?.click();};rail.querySelector('.prompt-actions').onclick=e=>{const action=e.target.dataset.action;if(!action)return;if(action==='lock'){const version={field_key:def.key,prompt:prompt.value,status:'LOCKED',version:`${def.code}-${Date.now()}`};store.state.prompts[`field:${def.key}`]=version;store.append('FIELD_PROMPT_VERSION',version);rail.querySelector('.prompt-status').textContent='LOCKED';return;}if(action==='regenerate'){document.querySelector('#run-builder')?.click();return;}const map={accept:'ACCEPTED',revise:'REVISED',reject:'REJECTED',defer:'DEFERRED'},status=map[action];if(status){const value=rail.querySelector('.controlled-suggestion')?.value||control.dataset.proposedValue||control.value||'';if(status==='ACCEPTED'||status==='REVISED')applyAcceptedValue(control,value);decideField(store,def.key,status,value,{prompt_version:store.state.prompts[`field:${def.key}`]?.version||'draft'});rail.querySelector('.answer-status').textContent=status;}};}
function collectConfig(doc,store){const fields=[...doc.querySelectorAll('.prompt-rail')].map(r=>{const key=r.dataset.fieldKey,def=Registry.fieldDefinition(key);return {...def,prompt:r.querySelector('.field-prompt').value,enabled:r.querySelector('.rail-enabled').checked};});const sections={};doc.querySelectorAll('[data-section]').forEach(c=>sections[c.dataset.section]={prompt:c.querySelector('textarea').value,enabled:c.querySelector('input').checked});const sourceText=doc.querySelector('[data-f=raw]')?.value||'',sourceCoordinates=doc.querySelector('[data-f=src_span]')?.value||'';const acceptedContext={};for(const e of store.state.events.filter(e=>e.type==='HUMAN_FIELD_DECISION'&&['ACCEPTED','REVISED'].includes(e.payload.status)))acceptedContext[e.payload.field_key]=e.payload.value;return {globalPrompt:'All model output is a proposal. Never admit, canonize, invent UUIDs, or force discoveries into schema fields.',builderPrompt:'Construct a complete candidate ATOM packet using stable field keys. Preserve source wording, provenance, validation vocabulary, and object-type boundaries.',sections,fields,sourceText,sourceCoordinates,acceptedContext,promptVersions:{global:'governance-v1',builder:'atom-builder-v1',sections:Object.fromEntries(Object.keys(sections).map(k=>[k,store.state.prompts[`section:${k}`]?.version||Registry.SECTION_PROMPTS[k].version])),fields:Object.fromEntries(fields.map(f=>[f.key,store.state.prompts[`field:${f.key}`]?.version||'draft']))}};}
function applyResults(doc,packet,store){for(const result of packet.field_results){const rail=doc.querySelector(`.prompt-rail[data-field-key="${CSS.escape(result.field_key)}"]`);if(!rail)continue;rail.querySelector('.answer-status').textContent='PROPOSED';rail.querySelector('.prompt-status').textContent='TESTED';rail.querySelector('.prompt-proposal').textContent=`${result.suggested_value??''}\n${result.rationale||''}`;rail.querySelector('.receipt').textContent=`${packet.builder_run_uuid} · confidence ${result.confidence} · anchors: ${(result.source_anchors||[]).join('; ')||'none'} · warnings: ${(result.warnings||[]).join('; ')||'none'}`;const control=rail.parentElement.querySelector('[data-f],[data-key]');const suggestion=rail.querySelector('.controlled-suggestion');if(suggestion&&[...suggestion.options].some(o=>o.value===result.suggested_value))suggestion.value=result.suggested_value;if(control)control.dataset.proposedValue=typeof result.suggested_value==='string'?result.suggested_value:JSON.stringify(result.suggested_value);rail.querySelector('.prompt-history').textContent=store.history('MODEL_RUN').map(e=>e.timestamp).join('\n')||'Recorded in run history.';}for(const d of packet.open_discoveries){store.state.discoveries.push(d);store.append('DISCOVERY_CREATED',d);}store.save();}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
return {CANDIDATE,ANSWER_STATUSES,PROMPT_STATUSES,RESPONSE_SCHEMA,AppendOnlyStore,composePrompt,createBuilderRequest,normalizePacket,validatePacket,runTwoPass,runException,addDiscovery,decideField,bulkDecide,applyAcceptedValue,mount};
});
