"""Controlled vocabularies — single source of truth shared with the frontend via /api/vocab.

Every dropdown in the UI is populated from here. Values are stable identifiers;
changing them requires a migration, not a UI edit.
"""

CANDIDATE_STATUS = "CANDIDATE_DRAFT — NOT ADMITTED"

CANON_STATUSES = [
    "CANDIDATE_DRAFT — NOT ADMITTED",
    "UNDER_REVIEW",
    "CANONICAL",
    "DEFERRED",
    "REJECTED",
    "SUPERSEDED",
    "CONTRADICTED",
]

RULING_DECISIONS = ["PROMOTE", "DEMOTE", "DEFER", "REJECT", "SUPERSEDE", "EDIT", "RESTORE"]

# --- Statements -------------------------------------------------------------
STATEMENT_MODES = [
    "DEFINITION",
    "LOGICAL",
    "MATHEMATICAL",
    "FORMAL_VERIFIED",
    "EMPIRICAL",
    "HISTORICAL",
    "PHILOSOPHICAL",
    "THEOLOGICAL",
    "BRIDGE",
    "ANALOGY",
    "CONJECTURE",
]

VERIFICATION_STATUSES = ["UNVERIFIED", "PARTIALLY_VERIFIED", "VERIFIED", "REFUTED", "NOT_RECOVERABLE"]

CONTRADICTION_STATUSES = ["NONE_KNOWN", "SUSPECTED", "ACTIVE", "RESOLVED"]

# --- Questions --------------------------------------------------------------
QUESTION_TYPES = [
    "DEFINITIONAL",
    "MECHANISTIC",
    "EVIDENTIAL",
    "LOGICAL",
    "MATHEMATICAL",
    "EMPIRICAL",
    "HISTORICAL",
    "PHILOSOPHICAL",
    "THEOLOGICAL",
    "METHODOLOGICAL",
    "BRIDGE",
    "SCOPE",
    "RIVAL_DISCRIMINATION",
    "OTHER",
]

ANSWER_STATUSES = ["UNANSWERED", "PARTIALLY_ANSWERED", "ANSWERED", "UNANSWERABLE", "DEFERRED"]

IMPORTANCE_LEVELS = ["LOW", "MODERATE", "HIGH", "CRITICAL", "UNKNOWN"]

# --- Evidence: nine burdens -------------------------------------------------
BURDEN_NAMES = [
    "SOURCE",
    "PROVENANCE_CUSTODY",
    "PROTOCOL",
    "CONDITIONS",
    "RAW_RECORD",
    "DERIVED_ARTIFACTS",
    "CONTROLS",
    "INDEPENDENCE_MAP",
    "DISCRIMINATION_STATEMENT",
]

BURDEN_STATES = [
    "NOT_STARTED",
    "PARTIAL",
    "SATISFIED",
    "SATISFIED_WITH_LIMITATION",
    "NOT_APPLICABLE",
    "IMPOSSIBLE_TO_RECOVER",
    "CONTRADICTED",
    "UNKNOWN",
]
# States that legally require a human-written rationale.
BURDEN_STATES_REQUIRING_RATIONALE = ["NOT_APPLICABLE", "IMPOSSIBLE_TO_RECOVER"]

EVIDENCE_CLASSES = [
    "instrument_readout",
    "physical_sample",
    "experimental_log",
    "observation",
    "image",
    "video",
    "audio",
    "manuscript",
    "inscription",
    "testimony",
    "survey",
    "interview",
    "database",
    "administrative_record",
    "archival_record",
    "computational_output",
    "simulation_output",
    "formal_proof",
    "source_code",
    "statistical_dataset",
    "secondary_analysis",
    "meta_analysis",
    "replication",
    "other",
]

EPISTEMIC_SOURCE_CLASSES = [
    "EMPIRICAL",
    "HISTORICAL",
    "TESTIMONIAL",
    "DOCUMENTARY",
    "COMPUTATIONAL",
    "MATHEMATICAL",
    "FORMAL_VERIFICATION",
    "OBSERVATIONAL",
    "EXPERIMENTAL",
    "SYNTHETIC",
]

EVIDENCE_DISTANCES = ["DIRECT", "ONE_INFERENCE", "MULTI_INFERENCE", "PROXY", "SURROGATE", "INDIRECT_ONLY"]

RELATIONS_TO_TARGET = [
    "MEASURES_TARGET",
    "MEASURES_CONSEQUENCE",
    "MEASURES_PREDICTOR",
    "MEASURES_PROXY",
    "EXCLUDES_RIVAL",
    "ESTABLISHES_BOUNDARY",
    "ESTABLISHES_MECHANISM",
]

UNCERTAINTY_TYPES = [
    "KNOWN_NUMERIC",
    "ESTIMATED",
    "INTERVAL",
    "DISTRIBUTIONAL",
    "SYSTEMATIC",
    "RANDOM",
    "CENSORING",
    "MISSINGNESS",
    "TRANSLATION",
    "CLASSIFICATION",
    "MODEL",
    "UNKNOWN",
]

SAMPLING_REGIMES = [
    "CENSUS",
    "RANDOM",
    "STRATIFIED",
    "CLUSTER",
    "CONVENIENCE",
    "PURPOSIVE",
    "SELF_SELECTED",
    "CASE_CONTROL",
    "COMPLETE_ARCHIVE",
    "SURVIVING_ARCHIVE",
    "UNKNOWN",
]

TIMING_OPTIONS = ["PROSPECTIVE", "RETROSPECTIVE", "POST_HOC", "UNKNOWN"]
HYPOTHESIS_TIMINGS = [
    "BEFORE_DATA",
    "BEFORE_ANALYSIS",
    "AFTER_DATA_BEFORE_ANALYSIS",
    "AFTER_ANALYSIS",
    "UNKNOWN",
]

REPLICATION_STATUSES = [
    "NOT_ATTEMPTED",
    "INTERNAL",
    "EXTERNAL",
    "CONCEPTUAL",
    "DIRECT",
    "MULTISITE",
    "FAILED",
    "MIXED",
]

REPLICATION_RELATIONS = [
    "SAME_DATA",
    "NEW_DATA_SAME_TEAM",
    "NEW_DATA_INDEPENDENT_TEAM",
    "NEW_METHOD_SAME_TARGET",
    "DIFFERENT_DOMAIN_SAME_STRUCTURE",
]

CONTROL_TYPES = [
    "NEGATIVE_CONTROL",
    "POSITIVE_CONTROL",
    "SHAM_CONTROL",
    "PLACEBO_CONTROL",
    "VEHICLE_CONTROL",
    "BASELINE_CONTROL",
    "BLANK_CONTROL",
    "CALIBRATION_STANDARD",
    "REFERENCE_STANDARD",
    "RANDOMIZED_CONTROL",
    "ACTIVE_COMPARATOR",
    "RIVAL_MECHANISM_CONTROL",
    "PERMUTATION_CONTROL",
    "ABLATION_CONTROL",
    "WRONG_ROLE_CONTROL",
    "NULL_MODEL",
    "COUNTERFACTUAL_CONTROL",
    "BLINDED_CONTROL",
    "DOUBLE_BLIND",
    "INTER_RATER",
    "REPLICATION",
    "NONE",
    "NOT_APPLICABLE",
]

ALTERNATIVE_EXPLANATIONS = [
    "MEASUREMENT_ERROR",
    "SAMPLING_BIAS",
    "SELECTION_EFFECT",
    "CONFOUNDING",
    "REVERSE_CAUSATION",
    "COMMON_CAUSE",
    "CHANCE",
    "MODEL_MISSPECIFICATION",
    "DATA_LEAKAGE",
    "OVERFITTING",
    "PUBLICATION_BIAS",
    "SURVIVORSHIP_BIAS",
    "REPORTING_BIAS",
    "EXPECTANCY_EFFECT",
    "OBSERVER_EFFECT",
    "INSTRUMENT_ARTIFACT",
    "CONTAMINATION",
    "DEPENDENT_SOURCE",
    "SEMANTIC_EQUIVOCATION",
    "ALTERNATIVE_MECHANISM",
    "UNKNOWN",
]

ALTERNATIVE_STATUSES = ["UNTESTED", "PARTIALLY_EXCLUDED", "STRONGLY_EXCLUDED", "FALSIFIED", "SURVIVES"]

# --- Evidence edges -----------------------------------------------------------
BEARINGS = [
    "SUPPORTS",
    "WEAKENS",
    "CONTRADICTS",
    "FALSIFIES",
    "NECESSARY_NOT_SUFFICIENT",
    "SUFFICIENT_NOT_NECESSARY",
    "CONSISTENT_WITH",
    "DISCRIMINATES_FROM",
    "DOES_NOT_DISCRIMINATE",
    "IRRELEVANT",
    "UNRESOLVED",
]

EXPECTED_UNDER_VALUES = ["VERY_UNLIKELY", "UNLIKELY", "NEUTRAL", "LIKELY", "VERY_LIKELY", "DETERMINED", "UNKNOWN"]

EDGE_STRENGTHS = ["STRONG", "MODERATE", "WEAK", "UNKNOWN"]

# --- Predictions --------------------------------------------------------------
PREDICTION_STATUSES = [
    "PROPOSED",
    "REGISTERED",
    "TESTING",
    "SUPPORTED",
    "NOT_SUPPORTED",
    "FALSIFIED_UNDER_TEST",
    "INCONCLUSIVE",
    "SUPERSEDED",
]

# --- Discovery Commons ----------------------------------------------------------
PROMOTION_ELIGIBILITY = ["ELIGIBLE", "NOT_YET", "NEVER", "UNKNOWN"]

# --- Sources / jobs ---------------------------------------------------------------
SOURCE_TYPES = ["MARKDOWN_FILE", "URL", "TRANSCRIPT", "PLAIN_TEXT", "OTHER"]
JOB_STATUSES = ["PENDING", "RUNNING", "SUCCEEDED", "FAILED", "CANCELLED"]
CALL_NUMBERS = [1, 2, 3]

# Candidate constraint-check status (truth constraint engine, Phase 5)
CONSTRAINT_STATUSES = [
    "CONSISTENT_WITH_TRUTH_SET",
    "ENTAILED_BY_TRUTH_SET",
    "REQUIRED_FOR_CLOSURE",
    "NEGATION_CONTRADICTS_TRUTH_SET",
    "INDEPENDENT",
    "CONTRADICTED",
    "UNDERDETERMINED",
]

VOCAB = {
    "CANDIDATE_STATUS": CANDIDATE_STATUS,
    "CANON_STATUSES": CANON_STATUSES,
    "RULING_DECISIONS": RULING_DECISIONS,
    "STATEMENT_MODES": STATEMENT_MODES,
    "VERIFICATION_STATUSES": VERIFICATION_STATUSES,
    "CONTRADICTION_STATUSES": CONTRADICTION_STATUSES,
    "QUESTION_TYPES": QUESTION_TYPES,
    "ANSWER_STATUSES": ANSWER_STATUSES,
    "IMPORTANCE_LEVELS": IMPORTANCE_LEVELS,
    "BURDEN_NAMES": BURDEN_NAMES,
    "BURDEN_STATES": BURDEN_STATES,
    "BURDEN_STATES_REQUIRING_RATIONALE": BURDEN_STATES_REQUIRING_RATIONALE,
    "EVIDENCE_CLASSES": EVIDENCE_CLASSES,
    "EPISTEMIC_SOURCE_CLASSES": EPISTEMIC_SOURCE_CLASSES,
    "EVIDENCE_DISTANCES": EVIDENCE_DISTANCES,
    "RELATIONS_TO_TARGET": RELATIONS_TO_TARGET,
    "UNCERTAINTY_TYPES": UNCERTAINTY_TYPES,
    "SAMPLING_REGIMES": SAMPLING_REGIMES,
    "TIMING_OPTIONS": TIMING_OPTIONS,
    "HYPOTHESIS_TIMINGS": HYPOTHESIS_TIMINGS,
    "REPLICATION_STATUSES": REPLICATION_STATUSES,
    "REPLICATION_RELATIONS": REPLICATION_RELATIONS,
    "CONTROL_TYPES": CONTROL_TYPES,
    "ALTERNATIVE_EXPLANATIONS": ALTERNATIVE_EXPLANATIONS,
    "ALTERNATIVE_STATUSES": ALTERNATIVE_STATUSES,
    "BEARINGS": BEARINGS,
    "EXPECTED_UNDER_VALUES": EXPECTED_UNDER_VALUES,
    "EDGE_STRENGTHS": EDGE_STRENGTHS,
    "PREDICTION_STATUSES": PREDICTION_STATUSES,
    "PROMOTION_ELIGIBILITY": PROMOTION_ELIGIBILITY,
    "SOURCE_TYPES": SOURCE_TYPES,
    "JOB_STATUSES": JOB_STATUSES,
    "CALL_NUMBERS": CALL_NUMBERS,
    "CONSTRAINT_STATUSES": CONSTRAINT_STATUSES,
}
